### ISSUE TITLE
Skip first cell?

### ISSUE THREAD

**Issue by TripwireNL** [mergesort/TableFlip#1]
Hi,

I really love this plugin! It's so easy to implement and works really well! I have a question though, is there an option to skip the first cell in the tableView? 

Thx!

**Comment by arpitdongre** [comment]
Hii @Tripwire999 , I don't think any such option available now though you can edit in the `UITableView+TableFlip.swift` itself & make it work. I have tried & it works. I can share code if you want. Thanks @mergesort  for this awesome library.

**Comment by mergesort** [comment]
Thanks @ArpitOnTheWay! I think that's the right answer, it doesn't feel like something the library should support outright @Tripwire999, since it's a very specific case. I'll think about how to handle configuration options for a bit, and see if anything generic comes to mind, and if it does I'll see if I can add your request.

I'll close this ticket while I think about that.

Thanks for the help and suggestions!
