### ISSUE TITLE
Animate all rows when we call tableView.reloadRows(at: [indexPath], with: .automatic)

### ISSUE THREAD

**Issue by indrajitsinh** [mergesort/TableFlip#5]
i am thinking that it might be a bug when i am try to reload a specific rows it will animate whole tableview , i just want to animate only rows that are in [indexPath]

```swift
     tableView.beginUpdates()
     tableView.reloadRows(at: [indexPath], with: .automatic)
     tableView.endUpdates()
```

**Comment by mergesort** [comment]
Hey @indrajitsinh. That call is not actually a part of TableFlip at all, it's just a standard in UITableView. If you have a bug when doing that, I think it's probably in your tableView's current implementation.

Can you be more specific about why you suspect it's related to TableFlip?

Thanks!

**Comment by indrajitsinh** [comment]
@mergesort  well it animate my whole tableview with fade effect , i never wrote any code to animate all the tableview cell in my tableView didSelectRowAt indexPath: IndexPath  delegate method , and there is only one place where i animate all the tableview cell is in viewDidLoad after when data is completely fetched from web service 

so my question is why it gonna animate all cell in tableView didSelectRowAt indexPath: IndexPath where i just  wrote 

```swift
     tableView.beginUpdates()
     tableView.reloadRows(at: [indexPath], with: .automatic)
     tableView.endUpdates()
```

**Comment by mergesort** [comment]
Just to make sure, are you asking if it's possible to animate just one table cell? 

TableFilp doesn't currently support animating only 1 cell, or an array of cells, just the entire `tableView`, since it was built to allow you to avoid calling `reloadData` and having to diff the `tableView` and `dataSource`.

If that's what you would like, I can consider adding support for animating just one cell, but it would still piggy back off of `reloadData`, and not `reloadRows`, since that's the library's intended purpose.

**Comment by mergesort** [comment]
It looks like you might be looking for something else. I'm going to close this out, but if you have any more questions or clarifications, feel free to re-open it.
