### ISSUE TITLE
Animate only specific section

### ISSUE THREAD

**Issue by alimoon88** [mergesort/TableFlip#9]
Hi,
It will be nice if we can animate specific section only when there are multiple visible sections.

**Comment by mergesort** [comment]
Hey @alimoon88. Thanks for the suggestion. Unfortunately the API for TableFlip works by looking at the current visible cells only, rather than specifically dealing with any IndexPaths, rows, or sections. I can think about restructuring this at another point in time if this is something you feel is quite important. Alternatively if you want to file a PR, I'd be happy to read it over and think through it.

Let me know!

**Comment by alimoon88** [comment]
Hi @mergesort, Thanks for your quick reply, just after adding the suggestion I modified the code and did exactly what I want, animating specific visible section cells.
[UITableView+TableFlip.swift.zip](https://github.com/mergesort/TableFlip/files/847968/UITableView.TableFlip.swift.zip)

**Comment by mergesort** [comment]
Hey @alimoon88. This actually looks like a pretty good solution, thanks! I'll play with it a bit and try and find some time to implement it.

I wish I could give you some fake internet points, but instead I'll just say, thanks again!

**Comment by mergesort** [comment]
Hey @alimoon88. It's a little delayed, but I went ahead and implemented the changes you requested in [this commit](https://github.com/mergesort/TableFlip/commit/7580525c3d1ba65bc6e2bc9dd9fa1f4bf5be8e25).

My implementation is a tiny bit different than yours, but your code was a terrific foundation, so thank you very much for the work. If you're using CocoaPods, you can also update to version 1.0.1, to get the changes in your app.

Thanks again!
